version: '3.6'

services:
  zookeeper:
    ports:
      - 2181:2181
    container_name: zookeeper
    build: 
      context: .
      dockerfile: zookeeper/Dockerfile
    networks:
      - kafka
    volumes:
      - ~/Desktop/kafka-zoo:/tmp/zookeeper
  server:
    ports:
      - 9092:9092
    container_name: server
    build: 
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - zookeeper
    env_file:
      - kafka.env
    networks:
      - kafka
    volumes:
      - ~/Desktop/kafka-data:/tmp/kafka-logs
  producer:
    container_name: producer
    build: 
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - zookeeper
      - server
    networks:
      - kafka

  consumer:
    container_name: consumer
    build: 
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - zookeeper
      - server
    networks:
      - kafka
networks:
  kafka:
